### PR TITLE
Finished `application-testing` & `database-testing`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by summerblue** [comment]
不给你 Review

**Comment by summerblue** [comment]
68747470733a2f2f7261772e6769746875622e636f6d2f6d616e6966657374696e7465726163746976652f6465766c6966652f6d61737465722f4465764c6966652e416469756d456d6f7469636f6e5365742f695f6469645f776861742e676966

**Comment by ghost** [comment]
非要这样耍脾气么。。。

image

**Comment by summerblue** [comment]
done review

**Pull request merged**
